import { fieldNames } from './fieldNames';
import { fieldTypes } from './fieldTypes';

export const bufferValues = [
  {
    value: '',
    label: 'Title',
    placeHolderText: 'Name of your Workshop',
    validations: {
      message: 'Please Type Title',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.text,
    name: fieldNames.title,
  },
  {
    value: '',
    label: 'Description',
    placeHolderText: 'Describe in a few words about your service offerings',
    validations: {
      message: 'Please Type Description',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.text,
    name: fieldNames.description,
  },
  {
    value: '',
    label: 'Primary Contact Number',
    validations: {
      message: 'Please Type Primary Contact Number',
      isValid: true,
      regex: /^[0-9]*$/,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.number,
    name: fieldNames.primaryContactNumber,
  },
  {
    value: '',
    label: 'Alternate Contact Number',
    validations: {
      message: 'Please Type Alternate Contact Number',
      isValid: true,
      regex: /^[0-9]*$/,
    },
    touched: false,
    allowValidation: false,
    fieldType: fieldTypes.number,
    name: fieldNames.alternateContactNumber,
  },
  {
    value: '',
    label: 'Payment Mode',
    placeHolderText: 'How the customer can pay for your services/offerings?',
    validations: {
      message: 'Please Select Payment Mode',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.multiselectbutton,
    name: fieldNames.paymentMode,
  },
  {
    value: '',
    label: 'Since',
    placeHolderText: 'Year Of Workshop Establishment',
    validations: {
      message: 'Please Type Since',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.text,
    name: fieldNames.since,
  },
  {
    value: '',
    label: 'Location',
    placeHolderText:
      'Indicate commonly known location like Saidapet, Velacherry',
    validations: {
      message: 'Please Type Location',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.text,
    name: fieldNames.location,
  },
  {
    value: '',
    label: 'Address',
    placeHolderText: 'Address with pincode',
    validations: {
      message: 'Please Type Address',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.textarea,
    name: fieldNames.address,
  },
  {
    value: '',
    label: 'Pincode',
    placeHolderText: 'Pincode',
    validations: {
      message: 'Please Type Pincode',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.number,
    name: fieldNames.pincode,
  },
  {
    value: '',
    label: 'Operation Hours',
    placeHolderText: 'Your regular working hours like 9 am to 6 pm',
    validations: {
      message: 'Please Type Operation Hours',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.text,
    name: fieldNames.operationHours,
  },
  {
    value: '',
    label: 'Week Off',
    placeHolderText: 'like All days, Sunday off, Monday 1/2 day, etc',
    validations: {
      message: 'Please Type Week Off',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.text,
    name: fieldNames.weekOff,
  },
  {
    value: '',
    label: 'Starting At',
    placeHolderText: 'Minimum service rate',
    validations: {
      message: 'Please Type Starting at',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldType: fieldTypes.number,
    name: fieldNames.startingAt,
  },
  {
    value: '',
    label: 'General Services and Oil Change',
    validations: {
      message: 'Please Select General Service & Oil Change',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldExtras: {
      isBoolean: true,
    },
    fieldType: fieldTypes.radio,
    name: fieldNames.generalServicesAndOilChange,
  },
  {
    value: '',
    label: 'Painting and Tinkering',
    validations: {
      message: 'Please Select Painting & Tinkering',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldExtras: {
      isBoolean: true,
    },
    fieldType: fieldTypes.radio,
    name: fieldNames.paintAndTinkering,
  },
  {
    value: '',
    label: 'AC Repair and Cleaning',
    validations: {
      message: 'Please Select CarWash AC Repair & Cleaning',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldExtras: {
      isBoolean: true,
    },
    fieldType: fieldTypes.radio,
    name: fieldNames.acAndCleaning,
  },
  {
    value: '',
    label: 'Car Wash',
    validations: {
      message: 'Please Select CarWash',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldExtras: {
      isBoolean: true,
    },
    fieldType: fieldTypes.radio,
    name: fieldNames.carWash,
  },
  {
    value: '',
    label: 'Wheels and Spares',
    validations: {
      message: 'Please Select Wheels & Spares',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldExtras: {
      isBoolean: true,
    },
    fieldType: fieldTypes.radio,
    name: fieldNames.wheelsAndSpares,
  },
  {
    value: '',
    label: 'ECU Coding',
    validations: {
      message: 'Please Select ECU Coding',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldExtras: {
      isBoolean: true,
    },
    fieldType: fieldTypes.radio,
    name: fieldNames.ecuCoding,
  },
  {
    value: '',
    label: 'Accessories',
    validations: {
      message: 'Please Select Accessories',
      isValid: true,
    },
    touched: false,
    allowValidation: true,
    fieldExtras: {
      isBoolean: true,
    },
    fieldType: fieldTypes.radio,
    name: fieldNames.accessories,
  },
];
