export const fieldNames = {
  title: 'title',
  description: 'garageDescription',
  primaryContactNumber: 'contact',
  alternateContactNumber: 'altContact',
  paymentMode: 'paymentMode',
  since: 'dateOfEst',
  location: 'location',
  address: 'address',
  pincode: 'pincode',
  operationHours: 'operationHours',
  weekOff: 'weekOff',
  startingAt: 'startingAt',
  generalServicesAndOilChange: 'garageServices.gsAndOil',
  paintAndTinkering: 'garageServices.pbAndT',
  acAndCleaning: 'garageServices.acAndCL',
  wheelsAndSpares: 'garageServices.wAndS',
  ecuCoding: 'garageServices.engAndEcu',
  accessories: 'garageServices.acc',
  carWash: 'garageServices.carWash',
};
